### ISSUE TITLE
PowerFile error!

### ISSUE THREAD

**Issue by getengqing** [daerduoCarey/SpatialTransformerLayer#10]
Hello,When I added the PowerFile layer to my caffe, I got the error:
/caffe/src/caffe/layers/power_file_layer.cpp: In instantiation of ‘void caffe::PowerFileLayer::LayerSetUp(const std::vector<caffe::Blob>&, const std::vector<caffe::Blob>&) [with Dtype = caffe::Half]’:
/caffe/src/caffe/layers/power_file_layer.cpp:85:1: required from here
/caffe/src/caffe/layers/power_file_layer.cpp:35:13: 错误：无法将左值‘std::basic_istream’绑定到‘std::basic_istream&&’
while(fin >> tmp && k < bottom[0]->count(1)) {
^
How can I solver it?

**Comment by daerduoCarey** [comment]
I think this should be your system issue. Not related with Spatial Transformer Layer. What I'm doing here is just to read some input from your txt file. Sorry.

**Comment by getengqing** [comment]
Thanks!
